gems: [jekyll-paginate]

# Dependencies
markdown:         redcarpet
highlighter:      pigments

# Setup
title:            Arduino Projects
tagline:          ''
description:      'Cool Do-It-Yourself projects with Arduino.'
url:              https://guifh.github.io/arduino/
baseurl:          /

author:
  name:           'guifh'

paginate:         5

disqus:
  id: "guifh"
  
github:
  repo:           https://github.com/guifh/arduino
